### ISSUE TITLE
Could not resolve "clerk:astro"

### ISSUE THREAD

**Issue by JacobWeinbren** [panteliselef/astro-with-clerk-auth#137]
Hi -
 
 Using the instructions you laid out on your README, I get this error. Do you know what might be causing it?
 
 Thanks,
 Jacob
 
 [ERROR] Could not resolve "clerk:astro"

    node_modules/astro-clerk-auth/dist/chunk-DUP22WC7.js:26:38:
      26 │ import { getClerkAuthInitState } from "clerk:astro";
         ╵                                       ~~~~~~~~~~~~~

  You can mark the path "clerk:astro" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

05:36:33 [ERROR] [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/astro-clerk-auth/dist/chunk-DUP22WC7.js:26:38: ERROR: Could not resolve "clerk:astro"
    at failureErrorWithLog (/Users/jacobweinbren/Documents/GitHub/Mappa/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/jacobweinbren/Documents/GitHub/Mappa/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
    at /Users/jacobweinbren/Documents/GitHub/Mappa/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
^C

**Comment by panteliselef** [comment]
Hey @JacobWeinbren thanks for reporting this. Could you try v0.5.0, while i investigate ?

**Comment by spiritledsoftware** [comment]
I am having the same issue. I will switch to 0.5.0 for the time being.

**Comment by panteliselef** [comment]
I've confirmed the issue and i'm working on a solution

**Comment by panteliselef** [comment]
I've reverted the changes that were causing this issue with `astro-clerk-auth@0.6.3`.

I'm leaving this open as I plan to come back to the previous solution and fix the core issue.
