### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS Bug

### ISSUE THREAD

**Issue by cameronapak** [panteliselef/astro-with-clerk-auth#167]
Hey `astro-clerk-auth` team, I'm running into an `ERR_TOO_MANY_REDIRECTS` error that I wanted to share. I've seen something very similar on https://github.com/clerk/javascript/issues/1436 but I can't seem to find the right fix.

I've implemented your Astro Clerk integration easily. Thank you for this!

However, I am running into an error and need some help.

Here's a screenshot of what I'm encountering: 

![CleanShot 2024-06-03 at 08 44 04@2x](https://github.com/panteliselef/astro-with-clerk-auth/assets/35306616/4f9a922c-a463-463d-9fdb-a04c3fb40a18)

Lots of users are running into this.

Some things to know: 
- The site is hosted on Netlify
- Running on v20.10.0 of node
- `"astro-clerk-auth": "^0.7.0"`

Let me know if there's any other information that's needed. Thanks!

You can visit the website it's on at https://faith.tools

**Comment by cameronapak** [comment]
Here is an error that I'm logging on the server:

```txt
Jun 3, 09:16:17 AM: 28b1cf00 ERROR  Error validating session: _ClerkAPIResponseError: Gone
    at SessionAPI.request (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:2689:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:9301:23
    at async callMiddleware (file:///var/task/node_modules/astro/dist/core/middleware/callMiddleware.js:21:10)
    at async RenderContext.render (file:///var/task/node_modules/astro/dist/core/render-context.js:149:22)
    at async App.render (file:///var/task/node_modules/astro/dist/core/app/index.js:233:18)
    at async Module.handler (file:///var/task/node_modules/@astrojs/netlify/dist/ssr-function.js:29:30)
    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:1960:15)
    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)
```

```js
 {
  toString: [Function (anonymous)],
  status: 410,
  clerkTraceId: '17d2869e8e91d12e981ae5b51f494a07',
  clerkError: true,
  errors: [
    {
      code: 'operation_deprecated',
      message: 'endpoint is deprecated and pending removal',
      longMessage: 'This endpoint is deprecated and will be removed in future versions. We strongly recommend switching to networkless verification using short-lived session tokens, which is implemented transparently in all recent SDK versions (e.g. NodeJS SDK https://clerk.com/docs/backend-requests/handling/nodejs#clerk-express-require-auth). For more details on how networkless verification works, refer to our Session Tokens documentation https://clerk.com/docs/backend-requests/resources/session-tokens.',
      meta: [Object]
    }
  ]
}
```

**Comment by cameronapak** [comment]
Some solutions people offer to solve the `ERR_TOO_MANY_REDIRECTS` error:
1. Make sure the server is synced with your current timezone. (Still unsure on how to do this on Netlify and if it's necessary)
2. Downgrade from node v20 to v18. I tried but ran into an issue where node v20+ was needed for a dep

**Comment by panteliselef** [comment]
Hey @cameronapak thanks for reaching out here. For faster communication i'd open an issue in the official Clerk discord server and tag me. 

Otherwise could you share what was the full url when this happened ? Also a few more steps on how to reproduce ? Like is this after signin/up or when people are logged out ?

**Comment by cameronapak** [comment]
I unfortunately don't have the full URL. However, I do know that clerk somewhere in the middleware attached a URL param to the URL. Only then is when I encountered the too many redirects bug. 

I did have the site server side rendered, but also cached... that may be the issue. Therefore, I've decided to approach it client-side. I'll do that soon.
